"""empty message

Revision ID: 84633a2b8f43
Revises: edc9a51de04c
Create Date: 2021-01-06 14:27:10.323253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84633a2b8f43'
down_revision = 'edc9a51de04c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_playlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playlist_name', sa.String(length=300), nullable=True),
    sa.Column('playlist_id', sa.String(length=300), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_playlist')
    # ### end Alembic commands ###
